all:
	g++ Python_to_C.cpp -o Python_to_C -lpython3.8 -I /usr/include/python3.8
	
clean:
	rm -rf states_binary.xml
	rm -rf states.xml
	rm -rf energy.xml
	rm -rf tiles.pickle
	rm -rf Python_to_C
	rm -rf Device_Model_Class.py
	touch tiles.pickle
	touch states_binary.xml
	touch states.xml
	touch energy.xml
